### ISSUE TITLE
Move namespace to petsupplystore

### ISSUE THREAD

**Issue by joakimkistowski** [DescartesResearch/Pet-Supply-Store#15]
tools.descartes.petstore -> tools.descartes.petsupplystore

don't forget to change poms, Service, web.xml, Eclipse context paths, etc.

**Comment by joakimkistowski** [comment]
We should probably close all active branches first

**Comment by NSchmittUniWue** [comment]
As far as I am concerned, branch issue_11 can be closed. I will merge the image branch into master, then we can move the namespace.

**Comment by SimonEismann** [comment]
moved
