### ISSUE TITLE
Every service throws IllegalStateExceptions when trying to shutdown properly.

### ISSUE THREAD

**Issue by NSchmittUniWue** [DescartesResearch/Pet-Supply-Store#18]
A `java.lang.IllegalStateException` is thrown for every service because the web application instance has been stopped already. The state exception is followed by a `javax.ws.rs.ProcessingException` because the event listener cannot be destroyed.

**Comment by SimonEismann** [comment]
Fixed this for all threads except for the datapublisher thread. Waiting on netflix fix for that one
