### ISSUE TITLE
Create images that contain animals

### ISSUE THREAD

**Issue by AndreBauerUniWue** [DescartesResearch/Pet-Supply-Store#19]

**Comment by NSchmittUniWue** [comment]
Do you want randomized positions or fixed like top left corner?

**Comment by NSchmittUniWue** [comment]
This issue needs a larger refactoring than anticipated. The image provider never did distinguish between categories while creating images on startup.

**Comment by NSchmittUniWue** [comment]
Image provider now can draw images for categories. v1 / v2 / v.... versions will have the same image as the first categories of the same animal species. Just need transparent CC0 licensed ferret, guinnea pig and hamster pictures to complete the list.
