### ISSUE TITLE
Warnings and Todos in the image provider

### ISSUE THREAD

**Issue by SimonEismann** [DescartesResearch/Pet-Supply-Store#21]
I was able to clean up the warnings across all projects, except for three warnings in the image provider.

The warnings concern some unused code in the TestRandomReplacement.java, i would rather not delete the code, in case it is still needed.

Additionally the SetupController.java contains two TODOs, either fix the TODOs or convert them to gitlab issues :-)

**Comment by NSchmittUniWue** [comment]
TODOs removed. No warnings in image provider. The current commits are NOT TESTED because the master branch is not usable.
