### ISSUE TITLE
Using a non-existing username throws an exception

### ISSUE THREAD

**Issue by SimonEismann** [DescartesResearch/Pet-Supply-Store#45]
Inputting a username that does not exist leads to an error being thrown. In general, the load balancer throws a timeout exception if the returned status code is not 200.

**Comment by SimonEismann** [comment]
Reminder to update store tests once this is fixed

**Comment by joakimkistowski** [comment]
Created loadbalancerexceptions branch to address the issue.
Load balancer now throws different exceptions depending on response error code.
TODO: Use these response in the services.

**Comment by SimonEismann** [comment]
Store now utilizes the responses
