### ISSUE TITLE
Image Provider claims image generation is finished even though it is not after database regeneration

### ISSUE THREAD

**Issue by joakimkistowski** [DescartesResearch/Pet-Supply-Store#50]

**Comment by NSchmittUniWue** [comment]
The intended behavior is as follows: The very first image provider will report ready as soon as he can service requests, even if the images are not fully generated yet. Follow up image provider services will only report ready and register when all images have been generated. This is intended as we always want at least one running instance servicing requests, even if queries to some images fail and an error image is returned. 

In case the persistence regenerates data, triggered via the web frontend, were already in a ready state until the new images are scheduled for creation. I added flag that sets the image provider's status to "not ready" in case a reconfiguration of the persistence takes place.
When this has been tested, this issue can be marked as resolved.

**Comment by joakimkistowski** [comment]
Tested and confirmed.
